=== iperez95/A2-XML_DTD_XSDFINAL/Biblio.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="tipo_clase_tipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="novela"/>
            <xs:enumeration value="infantil"/>
            <xs:enumeration value="didactico"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_clase_tipo_rev">
        <xs:restriction base="xs:string">
            <xs:enumeration value="informatica"/>
            <xs:enumeration value="corazon"/>
            <xs:enumeration value="coches"/>
            <xs:enumeration value="investigacion"/>
            <xs:enumeration value="otras"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_clase_tipo_perio">
        <xs:restriction base="xs:string">
            <xs:enumeration value="nacional"/>
            <xs:enumeration value="internacional"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_seccion_tipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="economica"/>
            <xs:enumeration value="opinion"/>
            <xs:enumeration value="deportes"/>
            <xs:enumeration value="nacional"/>
            <xs:enumeration value="internacional"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "libros">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="libro">
                                <xs:complexType>
                                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                        <xs:element name = "titulo" type= "xs:string" />
                                        <xs:element name = "indice" type ="xs:string" />
                                        <xs:element name = "sinopsis" type ="xs:string" />
                                        <xs:element name ="capitulos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="capitulo">
                                                        <xs:complexType>
                                                            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                                <xs:element name="titulo_capi"  type= "xs:string"/>
                                                                <xs:element name="contenido">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:string">
                                                                                <xs:attribute name="enlace" type="xs:string" use="required" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="cantidad_paginas" type="xs:integer" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="cantidad_paginas" type="xs:integer" use="required"/>
                                    <xs:attribute name="tipo_clase" type="tipo_clase_tipo" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "revistas">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="revista">
                                <xs:complexType>
                                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                        <xs:element name = "titulo_rev" type= "xs:string" />
                                        <xs:element name = "numero_rev" type ="xs:integer" />
                                        <xs:element name = "indice_rev" type ="xs:string" />
                                        <xs:element name ="secciones">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="seccion">
                                                        <xs:complexType>
                                                            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                                <xs:element name="contenido_rev">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:string">
                                                                                <xs:attribute name="enlace" type="xs:string" use="required"/>
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="num_pags" type="xs:integer" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="num_pags" type="xs:integer" use="required"/>
                                    <xs:attribute name="tipo_clase" type="tipo_clase_tipo_rev" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "periodicos">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="periodico">
                                <xs:complexType>
                                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                        <xs:element name = "indice_perio" type= "xs:string" />
                                        <xs:element name ="secciones_perio">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="seccion_perio">
                                                        <xs:complexType>
                                                            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                                <xs:element name="articulos">
                                                                    <xs:complexType>
                                                                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                                            <xs:element name="articulo">
                                                                                <xs:complexType>
                                                                                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                                                        <xs:element name="contenido_perio">
                                                                                            <xs:complexType>
                                                                                                <xs:simpleContent>
                                                                                                    <xs:extension base="xs:string">
                                                                                                        <xs:attribute name="enlace" type="xs:string" use="required"/>
                                                                                                    </xs:extension>
                                                                                                </xs:simpleContent>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="autor" type="xs:string" use="required"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="tipo_seccion" type="tipo_seccion_tipo" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="fecha_publ" type="xs:date" use="required"/>
                                    <xs:attribute name="tipo_clase" type="tipo_clase_tipo_perio" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== iperez95/A2-XML_DTD_XSDFINAL/Biblio.xml
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Biblio.xsd">
    <libros>
        <libro id="L-1234" tipo_clase="novela" cantidad_paginas="100">
            <titulo>Orgullo y prejuicio</titulo>
            <indice>
                Capitulo 1.
                Capitulo 2.
                Capitulo 3.
            </indice>
            <sinopsis>
                Con la llegada del rico y apuesto Mr. Darcy a su región, las vidas de los Bennet y sus cinco hijas se vuelven del revés.
                El orgullo y la distancia social, la astucia y la hipocresía, los malentendidos y los juicios apresurados abocan a sus
                personajes al escándalo y al dolor, pero también a la comprensión, el conocimiento y el amor verdadero.
            </sinopsis>
            <capitulos>
                <capitulo cantidad_paginas="10">
                    <titulo_capi> Capitulo 1</titulo_capi>
                        <contenido enlace="www.enlace.com"></contenido>
                </capitulo>
            </capitulos>
        </libro>
    </libros>

    <revistas>
        <revista id="R-1234" tipo_clase="investigacion" num_pags ="60">
            <titulo_rev>Revista n.5</titulo_rev>
            <numero_rev>5</numero_rev>
            <indice_rev>
                Seccion 1.
                Seccion 2.
                Seccion 3.
            </indice_rev>
            <secciones>
                <seccion num_pags="2">
                    <contenido_rev enlace="www.enlace.com">
                    </contenido_rev>
                </seccion>
            </secciones>
        </revista>
    </revistas>

    <periodicos>
        <periodico id="P-1234" tipo_clase = "internacional" fecha_publ ="2002-09-24">
            <indice_perio>
                Seccion 1.
                Seccion 2.
                Seccion 3.
            </indice_perio>
            <secciones_perio>
                <seccion_perio tipo_seccion="deportes">
                    <articulos>
                        <articulo autor="Miguel Angel García">
                            <contenido_perio enlace="www.enlace.com">
                            </contenido_perio>
                        </articulo>
                    </articulos>
                </seccion_perio>
            </secciones_perio>

        </periodico>
    </periodicos>

</biblioteca>
